services:
  gitea:
    container_name: gitea
    hostname: gitea.docker.localhost
    build:
      context: gitea
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      flipt_network:
        aliases:
          - gitea.docker.localhost
    environment:
      ROOT_URL: http://gitea.docker.localhost:3000/
      DOMAIN: gitea.docker.localhost
      DISABLE_REGISTRATION: "true"
      REQUIRE_SIGNIN_VIEW: "true"
      INSTALL_LOCK: "true"
      DB_TYPE: sqlite3
      SSH_DOMAIN: localhost
      HTTP_PORT: "3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5

  gitea-runner:
    container_name: gitea_act_runner
    image: gitea/act_runner:latest-dind-rootless
    privileged: true
    restart: always
    networks:
      - flipt_network
    depends_on:
      gitea:
        condition: service_healthy
        restart: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GITEA_INSTANCE_URL=http://gitea:3000
      - GITEA_RUNNER_NAME=3ad321497a7e
      - DOCKER_HOST=unix:///var/run/user/1000/docker.sock
      - GITEA_RUNNER_REGISTRATION_TOKEN=riyUbrkLdKNKXAw1yjZTpr3JKT35IAzuw8nc0w4C

  prometheus:
    container_name: prometheus
    networks:
      - flipt_network
    image: prom/prometheus:latest
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./prometheus/web-config.yml:/etc/prometheus/web-config.yml"
      - "./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml"
      - "./prometheus/http.config.yml:/etc/prometheus/http.config.yml"
    ports:
      - "9090:9090"
    command:
      - --web.enable-otlp-receiver
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.config.file=/etc/prometheus/web-config.yml
    healthcheck:
      test:
        [
          "CMD",
          "promtool",
          "check",
          "ready",
          "--http.config.file=/etc/prometheus/http.config.yml",
        ]
      interval: 10s
      timeout: 15s
      retries: 10
      start_period: 10s

  flipt:
    image: docker.flipt.io/flipt/flipt:v2
    container_name: flipt
    volumes:
      - "./flipt/config.yml:/etc/flipt/config/default.yml"
    depends_on:
      prometheus:
        condition: service_healthy
      gitea:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "9000:9000"
    networks:
      - flipt_network
    restart: always
    environment:
      - FLIPT_LOG_LEVEL=info
      - FLIPT_ANALYTICS_STORAGE_PROMETHEUS_ENABLED=true
      - FLIPT_ANALYTICS_STORAGE_PROMETHEUS_URL=http://prometheus:9090
      - PROMETHEUS_AUTH_TOKEN=Basic YWRtaW46cGFzc3dvcmQ=
      - FLIPT_META_TELEMETRY_ENABLED=false
      - FLIPT_META_CHECK_FOR_UPDATES=false
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
      # - FLIPT_LICENSE_KEY=XXXXX-XXXXX-XXXXXX-XXXXXX-XXXXXXXX-XX

    command: ["/flipt", "server"]
    healthcheck:
      test: ["CMD", "wget", "--spider", "-qO-", "http://localhost:8080/health"]
      interval: 10s
      timeout: 15s
      retries: 10
      start_period: 5s

  jaeger:
    image: jaegertracing/jaeger:2.10.0
    container_name: jaeger
    deploy:
      resources:
        limits:
          memory: 1200M
    restart: unless-stopped
    ports:
      - "16686:16686"
      - "4318:4318"
    networks:
      - flipt_network

  webapp:
    container_name: webapp
    build:
      context: webapp
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    networks:
      - flipt_network
    depends_on:
      hotel-service:
        condition: service_started

  hotel-service:
    container_name: hotel-service
    build:
      context: hotel-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - flipt_network
    depends_on:
      flipt:
        condition: service_healthy
      jaeger:
        condition: service_started
    environment:
      - FLIPT_URL=http://flipt:8080
      - FLIPT_NAMESPACE=default
      - FLIPT_ENVIRONMENT=onoffinc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
      - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://prometheus:9090/api/v1/otlp
      - OTEL_EXPORTER_OTLP_METRICS_HEADERS=Authorization=Basic YWRtaW46cGFzc3dvcmQ=
      - OTEL_SERVICE_NAME=hotel-service

  admin-service:
    container_name: admin-service
    hostname: admin.docker.localhost
    build:
      context: admin-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - flipt_network
    depends_on:
      flipt:
        condition: service_healthy
      jaeger:
        condition: service_started
      hotel-service:
        condition: service_started
    environment:
      - FLIPT_URL=http://flipt:8080
      - FLIPT_NAMESPACE=admin
      - FLIPT_ENVIRONMENT=onoffinc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
      - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://prometheus:9090/api/v1/otlp/v1/metrics
      - OTEL_EXPORTER_OTLP_METRICS_HEADERS=Authorization=Basic YWRtaW46cGFzc3dvcmQ=
      - OTEL_SERVICE_NAME=admin-service
      - PORT=8001
      - HOTEL_SERVICE_URL=http://hotel-service:8000

networks:
  flipt_network:
